//
//  UIColor+SILColors.m
//  Silicon Labs Bluetooth Smart App
//
//  Generated by Zeplin (by colden on 2/3/15).
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+SILColors.h"

@implementation UIColor (SILColors)

+ (UIColor *)sil_siliconLabsRedColor {
    return [UIColor colorNamed: @"sil_siliconLabsRedColor"];
}

+ (UIColor *)sil_regularBlueColor {
    return [UIColor colorNamed: @"sil_regularBlueColor"];
}

+ (UIColor *)sil_cardBackgroundColor {
    return [UIColor colorNamed: @"sil_cardBackgroundColor"];
}

+ (UIColor *)sil_backgroundColor {
    return [UIColor colorNamed: @"sil_backgroundColor"];
}

+ (UIColor *)sil_secondaryBackgroundColor {
    return [UIColor colorNamed: @"sil_secondaryBackgroundColor"];
}

+ (UIColor *)sil_subtleTextColor {
    return [UIColor colorNamed: @"sil_subtleTextColor"];
}

+ (UIColor *)sil_primaryTextColor {
    return [UIColor colorNamed: @"sil_primaryTextColor"];
}

#pragma mark - Old colors

+ (UIColor *)sil_strongBlueColor {
    return [UIColor colorNamed: @"sil_strongBlueColor"];
}

+ (UIColor *)sil_lightBlueColor {
    return [UIColor colorNamed: @"sil_lightBlueColor"];
}

+ (UIColor *)sil_lineGreyColor {
    return [UIColor colorNamed: @"sil_lineGreyColor"];
}

+ (UIColor *)sil_bgGreyColor {
    return [UIColor colorNamed: @"sil_bgGreyColor"];
}

+ (UIColor *)sil_refreshGreyColor {
    return [UIColor colorNamed: @"sil_refreshGreyColor"];
}

+ (UIColor *)sil_lightGreyColor {
    return [UIColor colorNamed: @"sil_lightGreyColor"];
}

+ (UIColor *)sil_bgWhiteColor {
    return [UIColor colorNamed: @"sil_bgWhiteColor"];
}

+ (UIColor *)sil_silverChaliceColor {
    return [UIColor colorNamed: @"sil_silverChaliceColor"];
}

+ (UIColor *)sil_boulderColor {
    return [UIColor colorNamed: @"sil_boulderColor"];
}

+ (UIColor *)sil_masala50pcColor {
    return [UIColor colorNamed: @"sil_masala50pcColor"];
}

+ (UIColor *)sil_masalaColor {
    return [UIColor colorNamed: @"sil_masalaColor"];
}

+ (UIColor *)sil_silverColor {
    return [UIColor colorNamed: @"sil_silverColor"];
}

+ (UIColor *)sil_yellowColor {
    return [UIColor colorNamed: @"sil_yellowColor"];
}
+ (UIColor *)sil_greenColor {
    return [UIColor colorNamed: @"sil_regularGreenColor"];
}

@end
